
﻿using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Diagnostics;



public partial class UPLOAD_FILE : System.Web.UI.Page
{
    SqlConnection con = new SqlConnection();
    DB_OPERTION obj = new DB_OPERTION();
    AesAlg aes = new AesAlg();
    static string path;
    static int id;
    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            SqlCommand cmd = new SqlCommand();
            cmd.CommandText = "select max(id) from file1";
            id = obj.max_id(cmd);
        }
    }
    protected void Button2_Click(object sender, EventArgs e)
    {
        path = "~/storefil/" + id + ".txt";
        FileUpload1.SaveAs(Server.MapPath(path));
        StreamWriter sw = new StreamWriter("F:\\PROJECT MINI\\wwwroot\\Homomorphic\\storefil\\one.txt");
        sw.Write("F:\\PROJECT MINI\\wwwroot\\Homomorphic\\storefil\\" + id + ".txt");
        sw.Close();
        SqlCommand cmd = new SqlCommand();
        cmd.CommandText = "select max(id) from file1";
        id = obj.max_id(cmd);

        cmd.CommandText = "insert into file1 values('" + id + "','" + TextBox1.Text + "','" + path + "','" + System.DateTime.Now.ToShortDateString() + "','" + Session["id"] + "')";
        obj.execute(cmd);


        while (true)
        {
            if (File.Exists("F:\\PROJECT MINI\\wwwroot\\Homomorphic\\storefil\\outp.txt"))
            {
                System.Threading.Thread.Sleep(2000);
                StreamReader rd = new StreamReader(@"F:\PROJECT MINI\wwwroot\Homomorphic\storefil\outp.txt");
                string a = rd.ReadToEnd();
                rd.Close();

                string[] arr = a.Split(' ');

                for (int i = 0; i < arr.Length - 1; i++)
                {
                    string res = aes.EncryptStringToBytes_Aes(arr[i]);

                    //cmd.CommandText = "select * from findex where fkey='" + res + "'";
                    //DataTable dt1 = obj.getdata(cmd);
                    //if (dt1.Rows.Count > 0)
                    //{
                    //    Response.Write("<script>alert('yes')</script>");
                    //}
                    //else
                    //{
                    cmd.CommandText = "insert into findex values('" + id + "','" + res + "')";
                    obj.execute(cmd);
                    //}
                }
                break;
            }
        }
        File.Delete(@"F:\PROJECT MINI\wwwroot\Homomorphic\storefil\outp.txt");


    }
    private void exealg(string nam)
    {

        ProcessStartInfo start = new ProcessStartInfo();
        start.Arguments = nam; //ok
        start.UseShellExecute = false;
        start.FileName = @"C:\Users\admin\Anaconda3\python.exe";
        start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
        start.RedirectStandardError = true;
        using (Process process = Process.Start(start))
        {
            using (StreamReader reader = process.StandardOutput)
            {
                string result = reader.ReadToEnd();
            }

            process.WaitForExit();
        }
    }
    protected void Button3_Click(object sender, EventArgs e)
    {
        StreamReader rd = new StreamReader(@"F:\PROJECT MINI\wwwroot\Homomorphic\storefil\12.txt");
        string a = rd.ReadToEnd();
        rd.Close();

        string[] arr = a.Split(' ');

        for (int i = 0; i < arr.Length - 1; i++)
        {
            string res = aes.EncryptStringToBytes_Aes(arr[i]);
            SqlCommand cmd = new SqlCommand();
            cmd.CommandText = "select max(id) from file1";
            int id = obj.max_id(cmd);
            cmd.CommandText = "insert into file1 values('" + id + "','" + TextBox1.Text + "','" + res + "','" + System.DateTime.Now.ToShortDateString() + "','" + Session["id"] + "')";
            obj.execute(cmd);
        }

    }
}
